config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'screenshots' => 'screenshots#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  def index
    url = params[:url]
    format = params[:format] || 'png'

    render text: 'url param is missing' and return if url.blank?


    session = Capybara::Session.new(:poltergeist)
    session.visit url

    file_name = "tmp/screenshots/#{Time.now.to_i}.#{format}"
    session.save_screenshot(file_name, :full => true, format: format)

    send_file file_name, disposition: 'inline'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Url2picture</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/screenshots/index.html.erb
<h1>Screenshots#index</h1>
<p>Find me in app/views/screenshots/index.html.erb</p>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">

  <%= form_tag screenshots_path, method: :get do %>
    <%= label_tag :url %>
    <%= text_field_tag :url %>
    <%= select_tag :format, options_from_collection_for_select([:png, :png, :gif], :to_s, :to_s)  %>
    <%= submit_tag 'Get Screenshot' %>
  <% end %>

  </div>
</div>